import React, { useState } from 'react';
import { motion } from 'framer-motion';
import GlassCard from '@/components/ui/GlassCard';
import { 
  ArrowLeft, ChevronDown, ChevronUp, Mail, MessageSquare
} from 'lucide-react';
import { Link } from 'react-router-dom';
import { createPageUrl } from '@/utils';
import { Button } from "@/components/ui/button";

const faqs = [
  {
    question: 'What is The Great Work?',
    answer: 'The Great Work is a system for self-discovery and personal growth based on archetypal psychology and ancient wisdom traditions. It helps you understand your inner patterns and guides your transformation journey.'
  },
  {
    question: 'How do the archetypes work?',
    answer: 'Each archetype represents a fundamental pattern of human consciousness. By engaging with them through journaling, conversations, and reflection, you activate and integrate different aspects of your psyche.'
  },
  {
    question: 'What is the Tree of Life?',
    answer: 'The Tree of Life is a map of consciousness from the Kabbalistic tradition. Each node (Sephira) corresponds to an archetype, and together they form a path of spiritual development.'
  },
  {
    question: 'How are insights generated?',
    answer: 'Insights are generated by analyzing your journal entries, conversations, and interactions with the archetypes. The system identifies patterns, themes, and areas for growth.'
  },
  {
    question: 'Is my data private?',
    answer: 'Yes, your personal data, journal entries, and insights are private and encrypted. Only you can access your information unless you explicitly choose to share with friends.'
  },
];

export default function HelpSupport() {
  const [expandedFaq, setExpandedFaq] = useState(null);

  const toggleFaq = (index) => {
    setExpandedFaq(expandedFaq === index ? null : index);
  };

  return (
    <div className="space-y-4 relative">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="space-y-2"
      >
        <Link 
          to={createPageUrl('Settings')}
          className="inline-flex items-center gap-2 text-white/50 hover:text-white/80 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span className="font-data text-[10px] uppercase tracking-wider">Back to Settings</span>
        </Link>
        
        <h1 className="font-occult text-3xl font-semibold text-gradient-gold tracking-wide text-center">
          Help & Support
        </h1>
        <div className="font-data text-xs text-white/70 tracking-[0.2em] uppercase text-center">
          Knowledge Archive
        </div>
        <div className="flex items-center justify-center gap-2 text-white/30 text-xs">
          ⟨ ? ✦ ? ⟩
        </div>
      </motion.div>

      {/* FAQs */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
      >
        <div className="font-data text-[10px] text-white/50 uppercase tracking-widest mb-2">
          Frequently Asked Questions
        </div>
        <GlassCard className="divide-y divide-white/10">
          {faqs.map((faq, index) => (
            <div key={index}>
              <button
                onClick={() => toggleFaq(index)}
                className="w-full flex items-center justify-between p-4 hover:bg-white/5 transition-colors"
              >
                <span className="font-data text-[11px] text-white/80 text-left pr-4">
                  {faq.question}
                </span>
                {expandedFaq === index ? (
                  <ChevronUp className="w-4 h-4 text-white/40 flex-shrink-0" />
                ) : (
                  <ChevronDown className="w-4 h-4 text-white/40 flex-shrink-0" />
                )}
              </button>
              {expandedFaq === index && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  className="px-4 pb-4"
                >
                  <p className="font-data text-[10px] text-white/50 leading-relaxed">
                    {faq.answer}
                  </p>
                </motion.div>
              )}
            </div>
          ))}
        </GlassCard>
      </motion.div>

      {/* Contact */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <div className="font-data text-[10px] text-white/50 uppercase tracking-widest mb-2">
          Contact Us
        </div>
        <GlassCard className="p-4 space-y-3">
          <p className="font-data text-[10px] text-white/60 leading-relaxed">
            Need more help? Our support team is here to assist you on your journey.
          </p>
          <a 
            href="mailto:support@thegreatwork.app"
            className="w-full"
          >
            <Button
              variant="ghost"
              className="w-full border border-white/20 bg-black/40 text-white/70 hover:text-white hover:bg-white/5 hover:border-white/40 font-data text-xs uppercase tracking-wider"
            >
              <Mail className="w-4 h-4 mr-2" />
              Contact Support
            </Button>
          </a>
        </GlassCard>
      </motion.div>

      {/* Footer */}
      <div className="text-center font-data text-[8px] text-white/20 tracking-widest pt-2">
        KNOWLEDGE IS POWER • SEEK AND YOU SHALL FIND
      </div>
    </div>
  );
}